version: "3.7"
services:
  homer:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    container_name: "homer"
    ports:
    - 8080:8080
    volumes:
    - "./:/app"
    - "./node_modules:/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
